### ISSUE TITLE
多次入睡

### ISSUE THREAD

**Issue by inttor** [441907002/SleepMonitorView#1]
如果一天内有多次睡眠怎么展示啊，哥。是应该直接把时间轴变为24小时的呢？还是有什么更好的解决方案呢？

**Comment by MasterChen1016** [comment]
项目中是去除了午睡，只保留了晚上睡眠数据

**Comment by inttor** [comment]
哥，睡眠阶段能不能加多一个快速眼动周期的类别啊TT
